### ISSUE TITLE
Logic Error on the Edges

### ISSUE THREAD

**Issue by pham-andrew** [andrewdpham3/Elementary-Cellular-Automata-Rule-45#1]
The edges have the if and elseif checks in the for loop applying the rule. They don't seem to be applying or something is canceling them out. I suspect the last else statement with the general case could somehow be canceling them. If you take a look at the left edge of generation 0 to gen 1, it's supposed to apply rule 8 and give us a 1. On the right edge it's supposed to apply rule 8 and give us a 1. In both cases we're getting a 0.

**Comment by juan1sanchez** [comment]
I believe the issue has been fixed.  Check it so we can close this.

**Comment by juan1sanchez** [comment]
I believe I have fixed the issue.  Please check to make sure it works so we can close this.

**Comment by pham-andrew** [comment]
Generation 1 to generation 2, right edge (cell 399), should be applying rule 2 resulting in a 0 directly under at generation 2, cell 399. It looks like we're getting a 1.

More specifically, cells[1197] should be 0 but it looks like 1.

**Comment by pham-andrew** [comment]
So as you guys pointed out, it was flipped. So it wasnt that the right edge was giving us a 1, the left edge was. Which is correct. I flipped the image and now it looks correctomundo!
